### ISSUE TITLE
configure dev dns

### ISSUE THREAD

**Issue by steveoh** [agrc/surface-water-quality#19]
<img width="634" alt="ScreenCapture at Thu Jun 10 16:04:51 MDT 2021" src="https://user-images.githubusercontent.com/325813/121603202-a5308600-ca05-11eb-90ee-92e8b8074fe1.png">

**Comment by nathankota** [comment]
INC1493876

**Comment by steveoh** [comment]
this looks done. please close when the inc is resolved.
