### ISSUE TITLE
order production dns

### ISSUE THREAD

**Issue by steveoh** [agrc/surface-water-quality#20]
wq.deq.utah.gov seems like a good option. Right now it redirects to http://mapserv.utah.gov/surfacewaterquality/

**Comment by stdavis** [comment]
Maybe it should be something like `surface-water-quality.ugrc.utah.gov`? @steveoh Do we want to put everything under *.ugrc.utah.gov? Will that make our lives easier?

**Comment by nathankota** [comment]
INC1493876

**Comment by steveoh** [comment]
please have the cloud machine assign the prod dns for `ut-dts-agrc-surface-wq-prod`

**Comment by nathankota** [comment]
INC1495527

**Comment by nathankota** [comment]
Prod DNS hits the correct remote address, but I also get the following:

![image](https://user-images.githubusercontent.com/15659642/123096338-3af7e800-d3ec-11eb-9f48-20766213083a.png)

**Comment by stdavis** [comment]
I just pushed a fix for the favicon.
